spring.application.name=employee-manangement-system

spring.datasource.url=jdbc:postgresql://localhost:5432/ems_db
spring.datasource.username=postgres
spring.datasource.password=Ashu@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true